# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c993cfce16d8e3fa74f0d6aca447806e103a90b2ebe88ef3034249144be30cf664bf46eef80eb6713796b70044abea19654814d017cf2cd9c257b0f8981c2b32

test:
  secret_key_base: e6faa7fec68668287f6daad63f7f445b4df59701eb3f0a732d083e8ad91a56cabc5153439cdefd42c49b836c88fdcb6f2f4058ae07282b131e587da10294a0e0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
